wichmann-lab/python-psignifit

__init__.py
Hey there Heiko,
when importing the package from a `sys.path` it only loaded the empty init file.
This should fix it now, making functions available by 
`import psignifit as ps`
=> BUG: import of psignifit did not reveal functions.

.travis.yml, psignifit/tests/test_CItest.py, setup.py
Enable continuous integration
- added a first fake test just to make sure CI is working
- fixed compatibility for older Python3 versions. Right now we support: 3.4, 3.5 and 3.6
=> enable continuous integration

psignifit/likelihood.py, psignifit/psignifit.py, psignifit/tests/test_CItest.py, psignifit/tests/test_basic.py
fixing Bugs with fixedPars, should now be a simple vector. For backward compatibility we squeeze any given array with more dimensions
To keep this running a few lines in the likelihood calculation had to change as they were otherwise trying to index scalars.
A test was also added, which checks that the two values set in the basic test case are actually fixed, i.e. that the Fit and borders values are actually the provided values.
=> Fixing fixedPars for now

psignifit/getStandardParameters.py
The wiki for `python-psignifit` suggested implementing the getStandardParameters function: https://github.com/wichmann-lab/python-psignifit/wiki/How-to-Get-Standard-Parameters. Because this is a function I was using quite often in my own projects, I ported the MATLAB implementation (https://github.com/wichmann-lab/psignifit/blob/master/getStandardParameters.m)
=> Port getStandardParameters from MATLAB implementation

psignifit/psigniplot.py
plt.show does not expect array arguments, but only a keyword block in newer matplotlib versions
https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.show.html
#54
=> Replace plt.show(0) by plt.show(block=False) #54

psignifit/psignifit.py
There's a small bug when trying to use estimateType 'mean'. Might be translation error from matlab.
=> small bugfix to estimateType == 'mean'

psignifit/psignifit.py
This change appears to fix [issue #67](https://github.com/wichmann-lab/python-psignifit/issues/67).
Core functions were returning an error in computing marginal distributions because `np.squeeze` was being called on a list. It's strange that this bug shows up now where presumably many other users should have encountered it. I suspect it might be caused by some update to `np.squeeze` to change its behaviour.
I have now adjusted to call on the `np.array` output of marginalize before entering in the list. Psignifit tests now pass, and `demo_001.py` produces a plot. 
However, I have not extensively tested whether this preserves the intended functionality of `marginalize` and the `results["marginals"]` values, nor whether this is specific to different versions of Python / numpy. Advice …
=> Fix bug on squeezing marginal distributions

psignifit/psigniplot.py
Whenever the library was imported in a notebook, it would cause an empty plot to appear. The reason was the use of plt.gca() in the function definition line (in the default arguments). This fix moves the call into the function such that it is not executed during import.
=> Empty plot fix

psignifit/psignifit.py
for the parameters other than threshold and width this check does not make sense
Issue #79
=> Removes unnecessary warnings on marginal checks

psignifit/_priors.py, psignifit/psignifit.py
Keep unnormalized priors and return them to the user instead of the normalized one: this way marginals and priors live in the same space and can be compared and plotted
=> Fix priors scaling

psignifit/_configuration.py, psignifit/tests/test_configuration.py
=> Fix check for fixed params when `fixed_params` is None

psignifit/_parameter.py, psignifit/_posterior.py, psignifit/tests/test_param_recovery.py, pytest.ini
The optimization of the parameters start with a coarse grid, that is then refined to a finer one around the MAP.
In the calculation of the bounds of the finer grid, the last point was omitted because of a off-by-one issue. The problem had no impact on the calculation of the maximum, because the final optimization is done using gradient descent. Fixing the issue, however, improves the plots and the checks on the posterior.
=> Fix the calculation of the fine grid

psignifit/_configuration.py, psignifit/tests/test_basic.py, psignifit/tests/test_configuration.py, psignifit/tests/test_param_recovery.py, psignifit/tests/test_posterior.py, pytest.ini
Removed the last sources of spurious warnings emitted while running tests.
@lschwetlick : please could you double check this commit ec4e71629b9974f90343a2fcd7ae8ab0046681ce ?
That warning was added by you but I actually think it is wrong. The warning was issued when in an experiment type different from equal asymptote the lambda and gamma where both set but different? If at all it should be the other way around, in the sense that we should warn _only_ in the equal asymptote case. Or am I misunderstanding something?
=> Really silence warnings in tests

psignifit/psigniplot.py
-  2D marginal plot. Automatic swapping of axes is removed because it was a very confusing behavior and only depended on the alphabetical order of the parameters (indices).
- priors plot fixed with same range as in MATLAB version. Previous version to set the range was hacky.
- bayes plot, which was missing in the python implementation, now implemented for all combinations of non-fixed parameters.
=> fixes all plot functions

psignifit/sigmoids.py, psignifit/tests/test_sigmoids.py
[updated]
Things that happened in this PR:
- I added tests for all the existing sigmoids that make sure that their implementation is correct. This includes _value, _slope, and _inverse
- I made the sigmoid tests more generic, they were testing always with PC=0.5, alpha=0.05, and threshold=0.5 . These settings do not exercise the code outside of the default values, which is why we missed a problem with negative sigmoids
- I refactored test code (`assert_sanity_checks`) from the class Sigmoid to a standalone function
- The value of Sigmoid.PC now remains consistent even for negative sigmoids, and can be used for plotting and other computations. The _value, _slope, and _inverse method should use Sigmoid._PC, which for negative sigmoid is equal to `1 - PC`
=> Improve sigmoid tests, fix bug in Gaussian._slope

psignifit/_configuration.py, psignifit/demos/demo_001.py, psignifit/demos/demo_002.py, psignifit/demos/demo_003.py, psignifit/demos/demo_004.py, psignifit/demos/demo_005.py, psignifit/demos/demo_006.py, psignifit/psignifit.py
First step for #92 : remove `estimate_type` parameter.
It was unused, and it was decided that we will rather *add* other types of parameter estimates to the Results object, rather than offering the estimates as alternative running modes.
The first commit removes the parameter, the second fixes typos I found while reading the demos
=> Remove estimate type parameter

psignifit/psignifit.py, psignifit/psigniplot.py, psignifit/tests/test_basic.py
This will allow to do the priors plot and the marginals plot with the correct range. These two plots only work in debug mode.
The plotting routines have been adjusted accordingly to use this new returned dict.
=> Return the bounds dictionary in debug mode

docs/_config.yml
For some reason warning directives do *not* work in readthedocs
=> docs: adds banner on top of book.

psignifit/_result.py, psignifit/tests/test_result.py
It had not been updated to the new format of the confidence interval dictionary: `{'0.95': [ci_min, ci_max], '0.9': ...}`
Fix #172
=> Fix computation of confidence interval `Result.threshold` method

docs/basic-usage.md, docs/examples/parameter_recovery_demo.md, docs/examples/priors.md, docs/examples/results-object.md, docs/how_to/How-to-Fix-Parameters.md, docs/how_to/How-to-Get-Thresholds-and-Slopes.md, psignifit/_result.py, psignifit/demos/parameters_estimates.ipynb, psignifit/psignifit.py, psignifit/psigniplot.py, psignifit/tests/test_basic.py, psignifit/tests/test_param_recovery.py, psignifit/tests/test_psignifit.py, psignifit/tests/test_result.py
Following the discussion in #173 this PR reinstates the attribute `Result.parameter_estimate`, which becomes a property of the `Result` object. Internally we can still use `Result.get_parameter_estimate`, but for the naive user the interface is the same as it used to be in version `4.2`.
Note that for symmetry I have renamed the the attributes and the method to `Result.parameter_estimate_MAP`, `Result.parameter_estimate_mean` and `Result.get_parameter_estimate` without the `s` after `parameter`. The naming convention is now consistent for all related attributes/methods.
The documentation is updated too effectively reversing the work done in #174 .
Along the way I discovered that a couple of tests were not working and would pass unconditionally. An helper function was unconditionally …
=> Reinstate `Result.parameter_estimate`

psignifit/psigniplot.py
This copies the behavior of the MATLAB version, in which the marginal is simply repeated along the singleton axis so a heatmap can still be drawn.
This fixes #158
=> Adds 2D marginals also for fixed params

psignifit/_posterior.py, psignifit/psigniplot.py, psignifit/sigmoids.py, psignifit/tests/test_sigmoids.py, psignifit/tools.py
Fix  #170 
See #170 for details, but in short there were two smells in the code: 1) every call to Sigmoid.__call__ was followed by a rescaling using lambda and gamma; 2) all other public methods of Sigmoid take lambda and gamma as parameters, except for __call__.
I moved the rescaling inside Sigmoid.__call__ and got rid of both
=> Move rescaling of psychometric function related to lambda and gamma in `Sigmoid` object

psignifit/sigmoids.py, tests/test_param_recovery.py, tests/test_sigmoids.py
... because the names are sometimes aliases for the same class, as discussed in PR #190
=> Parametrize tests using the sigmoid classes, not the names

docs/how_to/How-to-Get-Standard-Parameters.md
I tried to describe the function as best I knew how. Should we have a more in depth demonstration and tutorial, or do you think this is fine?
=> Add a docs page for the get_standard_parameters method.

docs/examples/advanced-options.md, docs/how_to/How-to-Change-the-Threshold-Percent-Correct.md
It also copies the same text to the "How-To Change the threshold percentage correct", also including a warning that this is WIP
=> Fixes formatting of warning in documentation for advanced options

docs/examples/advanced-options.md, docs/how_to/How-to-Change-the-Threshold-Percent-Correct.md, psignifit/_priors.py, psignifit/psigniplot.py
Fix #204 
- turned the Exception raised when `thresh_PC != 0.5` into a meaningful warning
- fixed the position of the CI over threshold in `plot_psychometric_function` then `thresh_PC != 0.5`
=> Allow setting `thresh_PC` to something other than 0.5

psignifit/_posterior.py, psignifit/_result.py, psignifit/_utils.py, psignifit/psignifit.py, psignifit/sigmoids.py, tests/test_numpy_scalars.py, tests/test_result.py
Do not return Numpy scalars, i.e. 0-D Numpy arrays. Use Python floats instead.
This does not have any numerical relevance, but makes the returned values easier to read, especially during interactive work and in the documentation. I am using this PR already in #211 .
I have solved this by introducing a new utility `cast_np_scalar`, which can be called unconditionally on anything. If the input is a numpy scalar it will be converted to a Python scalar (typically, float or int), otherwise it is a no-op. This is necessary because we have functions and methods both in `Result` and `Sigmoid` which work both with Numpy arrays and scalars. We don't want to touch the arrays.
All this is needed because Numpy 2 implemented [NEP 51](https://numpy.org/neps/nep-0051-scalar-representation.html) and numpy …
=> cast estimated parameters from Numpy scalars  to Python floats

.github/workflows/build-docs.yml, .github/workflows/cd-release.yml, .github/workflows/ci-tests.yml
=> build docs using oldest supported Python version and add Python 3.13 to CI tests and release workflows

docs/_config.yml, docs/_toc.yml, docs/how_to/How-to-Get-Proportion-Correct.md, psignifit/_result.py, psignifit/_utils.py, psignifit/tools.py, tests/test_numpy_scalars.py, tests/test_result.py
=> Add a `proportion_correct` method to the `Result` object to get proportion correct values from the fitted psychometric function

docs/_config.yml
it also changes the configuration to that the trackeback from erros are printed directly and not stored in logs which we cannot access when building it in a CI server
Fixes #223
=> Fixes timeout issue happening sometimes when building the docs

psignifit/_configuration.py, tests/test_configuration.py, tests/test_numpy_scalars.py, tests/test_param_recovery.py
Error and warning messages and sensible bounds for the parameters were discussed with @FelixWichmann .
Fixes #221
=> Fixed parms tests

tests/test_psignifit.py
These datasets were simulated and are included in the matlab version of psignifit. The tests check against the values obtained by matlab, with a "sensible" tolerance (1% relative tolerance, 0.1% absolute tolerance). With sensible I mean a tolerance that is in the range of what a user cares. 
Because there are already extensive tests that check for parameter recovery, I include here only some of the datasets:
- 2AFC and gaussian
- yes/no and gaussian
- 2AFC and logistic
- yes/no and logistic
The point is to have a rough check that the matlab and the python version return the same values, within a "sensible" range.
This PR closes #61
=> Add couple of more datasets to test against
