wichmann-lab/python-psignifit

- psignifit/psignifit.py
fixing
https://github.com/wichmann-lab/python-psignifit/issues/13
for now-> at some point rewrite this in accordance with MATLAB
> fix entirely deleting options bug in biasAna

- psignifit/psigniplot.py
Fixes wichmann-lab/python-psignifit#21
> fix use of custom axis handle passed as argument

- psignifit/conf.py
- psignifit/likelihood.py
- psignifit/psignifit.py
- psignifit/sigmoids.py
- psignifit/tests/test_likelihood.py
- psignifit/tests/test_sigmoids.py
- psignifit/typing.py
The functional api of sigmoids in the current refactoring branch 
is nice for accessing the sigmoid as a function of the percentage correct.
Unfortunately, this functional approach makes it
hard to also express corresponding
threshold and slope for any perc correct in a clean way.
This is why I would like to propose this object oriented sigmoid 
api as an alternative solution. 
We should discuss it here or in a future meeting. 
Currently I only refactored the threshold function 
to this new api. Threshold-CI and both slope functionalities
are missing.
> Sigmoid objects

- psignifit/conf.py
- psignifit/configuration.py
- psignifit/psignifit.py
- psignifit/result.py
- psignifit/tests/test_bounds.py
- psignifit/tests/test_conf.py
- psignifit/tests/test_data_consistency.py
- psignifit/tests/test_likelihood.py
- psignifit/tests/test_psignifit.py
- psignifit/tests/test_result.py
#35 
@otizonaizit I just noticed, that renaming the Conf class makes the diff-view quite messy. 
Feel free to revert commit 0ce9eccf to undo this change for your review, and we can redo it afterwards.
> Save and load psignifit result including configuration

- docs/references/index.rst
- psignifit/__init__.py
- psignifit/bias.py
> Refactor biasAna function to new API.

- psignifit/configuration.py
- psignifit/psignifit.py
- psignifit/result.py
- psignifit/tests/test_result.py
> Threshold / slope utility in result

- psignifit/psignifit.py
getSlopePC has a parenthesis in the wrong place
> getSlopePC parenthesis location fix

- psignifit/psigniplot.py
> bugfix: fixes dependency on latex for lambda, gamma and eta x-labels

- psignifit/tests/test_param_recovery.py
> simulation tests 

- psignifit/_posterior.py
- psignifit/_priors.py
- psignifit/psignifit.py
by returning marginals that has also integral of 1. In this way we can plot them together with the priors and it replicates MATLAB way of plotting.
> Fixes scaling for real

- psignifit/psigniplot.py
- psychometric function
- priors
> Fixes two plots

- psignifit/_posterior.py
- psignifit/_priors.py
- psignifit/psignifit.py
- psignifit/tests/test_param_recovery.py
- Add the ability to also fit threshold and width. 
- fixes the tests to check the fitting with fixed parameters
- add compatibility for numpy <2
> Fixed params

- psignifit/psigniplot.py
> Priors plot running

- psignifit/_configuration.py
- psignifit/_priors.py
- psignifit/_result.py
- psignifit/demos/demo_002.py
- psignifit/demos/demo_004.py
- psignifit/demos/demo_006.py
- psignifit/psignifit.py
- psignifit/psigniplot.py
- psignifit/sigmoids.py
- psignifit/tests/test_result.py
- psignifit/tools.py
> Percent correct to proportion correct

- conftest.py
- psignifit/tests/test_param_recovery.py
> adds best practice randomness handling in tests. 

- psignifit/demos/parameter_recovery_demo.ipynb
I still need to find out how/where this can be added to the docs
> adds demo notebook [WIP]

- psignifit/_result.py
- psignifit/psignifit.py
- psignifit/psigniplot.py
- psignifit/tests/test_basic.py
- psignifit/tests/test_result.py
This debug mode  saves the whole posterior mass and the priors functions
> Includes a debug mode in psignifit

- psignifit/psigniplot.py
For two plots:
- plot psychometric function
- plot marginal
> Make plot aesthetics equal to matlab 

- psignifit/_configuration.py
- psignifit/tests/test_configuration.py
> Set default CI method to "percentile" and add a test

- psignifit/psigniplot.py
Fix #147 
The fix is in the first commit, then the rest is small style fixes, mostly trailing whitespaces
> Fix that  `plot_psychometric_function` draws gamma incorrectly

- psignifit/psigniplot.py
Fix #151 
The previous implementation computed the quantiles of the x-axis
There's a bit of noise because my editor also deleted unnecessary space characters -- sorry about that
> Fix `plot_prior` to plot 25 and 75 percentile of prior

- psignifit/psigniplot.py
> correct plot_bayes [WIP]

- docs/examples/bias-analysis.md
- psignifit/psigniplot.py
Fixes #176.
Changes plot function and updates demo
> Fixes plot in interval bias analysis

- psignifit/psigniplot.py
a residual difference between the MATLAB plot and the python plot.
Fixes #151
> Fixes wrong position of black dot in prior plot

- psignifit/_confidence.py
- psignifit/tests/test_confidence.py
> Change mentions of "p-levels"

- docs/_config.yml
- docs/examples/priors.md
- psignifit/psigniplot.py
updates documentation on priors
- explanation default priors
- how to change stimulus range for adaptive procedures
- pass a custom prior function
- check information against matlab wiki
updates also function that plots psychometric function,
- adds a parameter to scale the marker size for the data
> Updates documentation - Priors

- psignifit/_priors.py
- tests/test_basic.py
- tests/test_priors.py
Partial fix for #204 , I implemented my recommendations for fixing the `alpha_width` configuration
> Fix alpha_width config

- docs/_config.yml
- docs/examples/advanced-options.md
I started fixing the advanced options page for #83. I already made this PR now because I will have some questions about some of the options, and some clearly dont work yet, like alpha_width.
> Update Docs: advanced options page

- psignifit/sigmoids.py
- psignifit/tools.py
This PR together with #203 fixes #183 , at least for the "public" part of the API
> Revise docstrings in `sigmoids.py` and `tools.py`

- psignifit/psigniplot.py
> Fixes block number plotting in psigniplot model fit

- .github/workflows/ci-tests.yml
> Add to the matrix Python==3.12, numpy==1.26.4
